name: Release Workflow

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    name: Release Pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up NodeJs
        uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      - name: npm install -g
        run: |
          npm install -g hexo-cli
          npm install -g ejs@2.7.4
      - name: npm install
        run: |
          npm install
          npm install -S hexo-generator-json-content
          npm install hexo-deployer-git --save
          cd themes/hueman && npm install
      - name: Generate static files
        run: hexo g
      - name: Executing remote ssh commands - pre
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_DEPLOY_SERVER }}
          username: ${{ secrets.SSH_DEPLOY_USER }}
          port: ${{ secrets.SSH_DEPLOY_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.SSH_DEPLOY_PATH }} && docker-compose down
            rm -rf ${{ secrets.SSH_DEPLOY_PATH }}/public/*
      - name: Copy contents via ssh key
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.SSH_DEPLOY_SERVER }}
          USERNAME: ${{ secrets.SSH_DEPLOY_USER }}
          PORT: ${{ secrets.SSH_DEPLOY_PORT }}
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          source: public
          target: ${{ secrets.SSH_DEPLOY_PATH }}
      - name: Executing remote ssh commands - post
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_DEPLOY_SERVER }}
          username: ${{ secrets.SSH_DEPLOY_USER }}
          port: ${{ secrets.SSH_DEPLOY_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.SSH_DEPLOY_PATH }} && docker-compose up -d

