name: Release Workflow

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    name: Release Pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up NodeJs
        uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      - name: npm install
        run: |
          npm install -g hexo-cli
          npm install
      - name: Generate static files
        run: hexo -g
      - name: Copy contents via ssh key
        uses: appleboy/scp-action@master
        env:
          HOST: ${{ secrets.SSH_DEPLOY_SERVER }}
          USERNAME: ${{ secrets.SSH_DEPLOY_USER }}
          PORT: ${{ secrets.SSH_DEPLOY_PORT }}
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          source: "public"
          target: "${{ secrets.SSH_DEPLOY_PATH }}/public"
          rm: true


